#!/usr/bin/env node
// Independent fixture generator for `railgunners_core::transaction_call`.
//
// This script never uses the Rust decoder. It builds calldata with `ethers`
// from the pinned Railgun ABIs and produces V3 ciphertext with the same
// `@noble/ciphers` XChaCha20-Poly1305 implementation the upstream engine uses.
// Note plaintext material and commitment hashes come from the upstream engine
// V2 interop fixtures so the vectors stay interoperable with a separate
// generation path.
//
// Provenance:
//   - ABI source: Railgun-Community/engine @ 6e2614d53a106dd62abad91e7ce03ee4a3956138
//     src/abi/V2.1/RailgunSmartWallet.json, src/abi/V2/RelayAdapt.json,
//     src/abi/V3/PoseidonMerkleVerifier.json
//   - V2 note material: Railgun-Community/engine @ a9da11d3dc359671cd337242e96d5ce6571cca09,
//     generated by src/test/generate-v2-interop-fixtures.ts into
//     reference/generated-v2-transaction-fixtures.json
//   - ABI encoding: ethers 6.14.3 `Interface.encodeFunctionData`
//   - V3 ciphertext: @noble/ciphers 0.4.0 `xchacha20poly1305`, nonce expansion
//     with @noble/hashes 1.3.2 `sha256`
//
// Run with the engine's node_modules on NODE_PATH:
//   NODE_PATH=<engine>/node_modules node generate.cjs [upstream-v2-fixtures.json]
//
// Proofs are intentionally dummy values: these fixtures exercise calldata
// decoding and note decryption interoperability, not proof or chain validity.

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const ethers = require('ethers');
const { xchacha20poly1305 } = require('@noble/ciphers/chacha');
const { sha256 } = require('@noble/hashes/sha256');

const ENGINE_REV = '6e2614d53a106dd62abad91e7ce03ee4a3956138';
const NOTE_REV = 'a9da11d3dc359671cd337242e96d5ce6571cca09';
// Research root for the checked-out monorepo layout; override with RESEARCH_ROOT.
const RESEARCH_ROOT =
  process.env.RESEARCH_ROOT || path.resolve(__dirname, '../../../../../../research');
const ENGINE_DIR = process.env.ENGINE_DIR || path.join(RESEARCH_ROOT, '.tmp/engine');
const upstreamPath =
  process.argv[2] || path.join(RESEARCH_ROOT, 'reference/generated-v2-transaction-fixtures.json');
const outputPath = path.join(__dirname, 'fixtures.json');

// Highest 72-bit value. A `uint48` bound-params model (used for hashing) cannot
// represent this, so decoding it proves the transaction-call ABI uses uint72.
const MAX_UINT72 = (1n << 72n) - 1n;

const ZERO_20 = `0x${'00'.repeat(20)}`;
const ZERO_32 = `0x${'00'.repeat(32)}`;
const ZERO_31 = `0x${'00'.repeat(31)}`;

const hex = (value, bytes) => ethers.hexlify(value).slice(2).padStart(bytes * 2, '0');

function loadAbi(dir, relative) {
  return JSON.parse(fs.readFileSync(path.join(dir, relative), 'utf8'));
}

function dummyProof() {
  return {
    a: { x: 0n, y: 0n },
    b: { x: [0n, 0n], y: [0n, 0n] },
    c: { x: 0n, y: 0n },
  };
}

function v2CiphertextFromFixture(entry) {
  return {
    ciphertext: entry.ciphertext.map((word) => `0x${word}`),
    blindedSenderViewingKey: `0x${entry.blindedSenderViewingKey}`,
    blindedReceiverViewingKey: `0x${entry.blindedReceiverViewingKey}`,
    annotationData: `0x${entry.annotationData}`,
    memo: `0x${entry.memo}`,
  };
}

function v2Transaction(fixture, minGasPrice) {
  const bound = fixture.transactionV2.boundParams;
  return {
    proof: dummyProof(),
    merkleRoot: ZERO_32,
    nullifiers: [],
    commitments: fixture.transactionV2.commitments.map((value) => `0x${value}`),
    boundParams: {
      treeNumber: 0,
      minGasPrice,
      unshield: 0,
      chainID: 31337n,
      adaptContract: ZERO_20,
      adaptParams: ZERO_32,
      commitmentCiphertext: bound.commitmentCiphertext.map(v2CiphertextFromFixture),
    },
    unshieldPreimage: {
      npk: ZERO_32,
      token: { tokenType: 0, tokenAddress: ZERO_20, tokenSubID: 0n },
      value: 0n,
    },
  };
}

function main() {
  const upstream = JSON.parse(fs.readFileSync(upstreamPath, 'utf8'));
  const byId = new Map(upstream.fixtures.map((fixture) => [fixture.id, fixture]));
  const hidden = byId.get('v2-hidden-empty-memo');
  const shortMemo = byId.get('v2-hidden-short-memo');
  const visible = byId.get('v2-visible-sender-memo');
  if (!hidden || !shortMemo || !visible) {
    throw new Error('expected upstream V2 fixtures are missing');
  }

  const v2Abi = loadAbi(ENGINE_DIR, 'src/abi/V2.1/RailgunSmartWallet.json');
  const relayAbi = loadAbi(ENGINE_DIR, 'src/abi/V2/RelayAdapt.json');
  const v3Abi = loadAbi(ENGINE_DIR, 'src/abi/V3/PoseidonMerkleVerifier.json');
  const v2Interface = new ethers.Interface(v2Abi);
  const relayInterface = new ethers.Interface(relayAbi);
  const v3Interface = new ethers.Interface(v3Abi);

  const acceptedTx = v2Transaction(hidden, MAX_UINT72);
  const v2Accepted = v2Interface.encodeFunctionData('transact', [[acceptedTx]]);
  const selectorOf = (iface, name) => iface.getFunction(name).selector;

  const relayTx = v2Transaction(hidden, 0n);
  const actionData = {
    random: ZERO_31,
    requireSuccess: false,
    minGasLimit: 0n,
    calls: [],
  };
  const v2Relay = relayInterface.encodeFunctionData('relay', [[relayTx], actionData]);

  const twoTransactions = v2Interface.encodeFunctionData('transact', [
    [
      v2Transaction(shortMemo, 1n),
      v2Transaction(visible, 2n),
    ],
  ]);

  const empty = v2Interface.encodeFunctionData('transact', [[]]);

  const missingOutputTx = v2Transaction(hidden, 3n);
  missingOutputTx.boundParams.commitmentCiphertext = [];
  const missingOutput = v2Interface.encodeFunctionData('transact', [[missingOutputTx]]);

  // ABI-canonical but not a BN254 field element, to exercise field validation.
  const invalidCommitmentTx = v2Transaction(hidden, 4n);
  invalidCommitmentTx.commitments = [`0x${'ff'.repeat(32)}`];
  invalidCommitmentTx.boundParams.commitmentCiphertext = [];
  const invalidCommitment = v2Interface.encodeFunctionData('transact', [[invalidCommitmentTx]]);

  // V3 reuses the upstream hidden-empty-memo note material but encrypts the V3
  // plaintext layout independently with the upstream engine's noble cipher.
  const storedNonce = ethers.getBytes('0x000102030405060708090a0b0c0d0e0f');
  // Canonical V3 plaintext order: encodedMPK | random | value | tokenHash | senderRandom | memo.
  const v3Plaintext =
    hidden.note.encodedMPKHex +
    hidden.note.random +
    hidden.note.valueHex +
    hidden.note.tokenHash +
    hidden.note.senderRandom;
  const sharedKey = hidden.derivation.sharedKey;
  const cipherKey = ethers.getBytes(`0x${sharedKey}`);
  const nonceExtended = sha256(storedNonce).slice(0, 24);
  const encryptedBundle = xchacha20poly1305(cipherKey, nonceExtended).encrypt(
    ethers.getBytes(`0x${v3Plaintext}`),
  );
  const v3Ciphertext = `0x${hex(storedNonce, 16)}${hex(encryptedBundle, encryptedBundle.length)}`;

  const v3Transaction = {
    proof: dummyProof(),
    merkleRoot: ZERO_32,
    nullifiers: [],
    commitments: hidden.transactionV2.commitments.map((value) => `0x${value}`),
    boundParams: {
      treeNumber: 0,
      commitmentCiphertext: [
        {
          ciphertext: v3Ciphertext,
          blindedSenderViewingKey: `0x${hidden.derivation.blindedSenderViewingKey}`,
          blindedReceiverViewingKey: `0x${hidden.derivation.blindedReceiverViewingKey}`,
        },
      ],
    },
    unshieldPreimage: {
      npk: ZERO_32,
      token: { tokenType: 0, tokenAddress: ZERO_20, tokenSubID: 0n },
      value: 0n,
    },
  };
  const shieldRequest = {
    ciphertext: { encryptedBundle: [ZERO_32, ZERO_32, ZERO_32], shieldKey: ZERO_32 },
    preimage: {
      npk: ZERO_32,
      token: { tokenType: 0, tokenAddress: ZERO_20, tokenSubID: 0n },
      value: 0n,
    },
  };
  const globalBoundParams = {
    minGasPrice: 1n,
    chainID: 31337n,
    senderCiphertext: `0x${'ab'.repeat(8)}`,
    to: ZERO_20,
    data: '0x',
  };
  const unshieldChangeCiphertext = {
    encryptedBundle: [ZERO_32, ZERO_32, ZERO_32],
    shieldKey: ZERO_32,
  };
  const v3Execute = v3Interface.encodeFunctionData('execute', [
    [v3Transaction],
    [shieldRequest],
    globalBoundParams,
    unshieldChangeCiphertext,
  ]);

  const note = {
    receiverMasterPublicKey: hidden.receiver.masterPublicKeyHex,
    receiverViewingPrivateKey: hidden.receiver.viewingPrivateKey,
    receiverViewingPublicKey: hidden.receiver.viewingPublicKey,
    commitment: hidden.note.commitmentHash,
    sharedKey,
    blindedSenderViewingKey: hidden.derivation.blindedSenderViewingKey,
    blindedReceiverViewingKey: hidden.derivation.blindedReceiverViewingKey,
  };

  const payload = {
    provenance: {
      noteMaterial: {
        repository: 'Railgun-Community/engine',
        commit: NOTE_REV,
        fixture: 'reference/generated-v2-transaction-fixtures.json',
        generator: 'src/test/generate-v2-interop-fixtures.ts',
      },
      abi: {
        repository: 'Railgun-Community/engine',
        commit: ENGINE_REV,
        files: [
          'src/abi/V2.1/RailgunSmartWallet.json',
          'src/abi/V2/RelayAdapt.json',
          'src/abi/V3/PoseidonMerkleVerifier.json',
        ],
      },
      independentEncoders: {
        abi: 'ethers 6.14.3 Interface.encodeFunctionData',
        v3Ciphertext: '@noble/ciphers 0.4.0 xchacha20poly1305',
        v3Nonce: '@noble/hashes 1.3.2 sha256',
      },
      procedure:
        'node generate.cjs <upstream-v2-fixtures.json>; proofs are dummy and fixtures are not chain-valid',
    },
    selectors: {
      v2Transact: selectorOf(v2Interface, 'transact'),
      v2Relay: selectorOf(relayInterface, 'relay'),
      v3Execute: selectorOf(v3Interface, 'execute'),
    },
    note,
    v2Accepted: {
      kind: 'V2Transact',
      selector: selectorOf(v2Interface, 'transact'),
      calldata: v2Accepted,
      commitment: note.commitment,
    },
    v2RelayAccepted: {
      kind: 'V2Relay',
      selector: selectorOf(relayInterface, 'relay'),
      calldata: v2Relay,
      commitment: note.commitment,
    },
    v2TwoTransactions: {
      kind: 'V2Transact',
      selector: selectorOf(v2Interface, 'transact'),
      calldata: twoTransactions,
      commitments: [shortMemo.note.commitmentHash, visible.note.commitmentHash],
    },
    v2Empty: {
      kind: 'V2Transact',
      selector: selectorOf(v2Interface, 'transact'),
      calldata: empty,
    },
    v2MissingOutput: {
      kind: 'V2Transact',
      selector: selectorOf(v2Interface, 'transact'),
      calldata: missingOutput,
      commitment: note.commitment,
    },
    v2InvalidCommitment: {
      kind: 'V2Transact',
      selector: selectorOf(v2Interface, 'transact'),
      calldata: invalidCommitment,
    },
    v3Accepted: {
      kind: 'V3Execute',
      selector: selectorOf(v3Interface, 'execute'),
      calldata: v3Execute,
      commitment: note.commitment,
      storedNonce: ethers.hexlify(storedNonce).slice(2),
    },
  };

  fs.writeFileSync(outputPath, `${JSON.stringify(payload, null, 2)}\n`);
  console.log(`wrote ${outputPath}`);
}

main();
